# Site settings
title: "Mile High Hope Dealers - HA of Colorado"
description: Heroin Anonymous of Colorado Area Site

# Files
baseurl:
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png
discus_shortname: HAColorado
email: MileHighHopeDealers@gmail.com
url: "http://madforjekyll.github.io"
search: true
share: true
comments: true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name:   Heroin Anonymous of Colorado
  avatar: avatar.jpg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Mile High Hope Dealers is the website for the Colorado Area of Heroin Anonymous

# Social networking links used in footer. Update and remove as you like.
twitter_username: StarPerfect
github_username: StarPerfect
instagram_username: ST4RP3RF3CT

 
# Internal nav
nav:
 literature: "root_url/literature/"
 gallery: "root_url/gallery/"
 about: "root_url/about/"


# Server
destination:      	 ./_site
port:             	 4000


#dependencies
# Gems
gems:
  - jekyll-paginate


# Build settings
highlighter:         rouge
markdown:           kramdown
kramdown:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
paginate: 5
paginate_path: "/literature/page:num/"
permalink: "/literature/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-xxxxxxxx-x
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         


# Jekyll Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  